/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tampilan;

import Kelas.Product;
import Kelas.Category;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author cherly
 */
public class ProductFrame extends javax.swing.JFrame {

    /**
     * Creates new form ProductFrame
     */
    public ProductFrame() {
        initComponents();
        load_table();
        ComboBox();
        reset();
    }
    
    void reset(){
        autoId();
        tID.setText(null);
        tNama.setText(null);
        tPrice.setText(null);
        tDescription.setText(null);
        cbCategory.setSelectedItem(null);
    }
    
    void autoId() {
        try {
            Product prdID = new Product();
            ResultSet rs = prdID.autoId();
            
            if (rs.next()) {
                int id = rs.getInt("ID") + 1;
                tID.setText(String.valueOf(id));
            }else {
                tID.setText("1");
            }
        } catch (SQLException sQLException) {
             JOptionPane.showMessageDialog(null, "EROR :" + sQLException.getMessage());
        }
    }
    
    void ComboBox() {
        try {
            Category value = new Category();
            ResultSet rs = value.dataComboBox();
            
            while (rs.next()) {
                String data = rs.getString("categoryName");
                cbCategory.addItem(data);
                
            }
        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, " EROR : " + sQLException.getMessage());
        }
    }
    
    void load_table(){
        DefaultTableModel model = new DefaultTableModel();
        Product prd = new Product();
        model.addColumn("ID");
        model.addColumn("Nama");
        model.addColumn("Category");
        model.addColumn("Description");
        model.addColumn("Price");
        
        ResultSet rs = prd.TampilProduct();
        try {

            while (rs.next()){
               int id = rs.getInt("productId");
               String name = rs.getString("productName");
               String category = rs.getString("categoryName");
               String description = rs.getString("productDescription");
               int price = rs.getInt("productPrice");
               
               Object[] data = {id, name, category, description, price};
               model.addRow(data);
            }
            
        } catch (SQLException sQLException) {
            System.out.println("Eror : " + sQLException.getMessage());
        }
        tblProduct.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tID = new javax.swing.JTextField();
        tNama = new javax.swing.JTextField();
        tPrice = new javax.swing.JTextField();
        tDescription = new javax.swing.JTextField();
        cbCategory = new javax.swing.JComboBox<>();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(669, 420));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("PRODUCT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 6, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 55, 20, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 111, 32, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Category");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 167, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Description");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 223, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Price");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 273, 130, -1));
        getContentPane().add(tID, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 77, 137, -1));
        getContentPane().add(tNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 133, 137, -1));
        getContentPane().add(tPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 295, 137, -1));

        tDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDescriptionActionPerformed(evt);
            }
        });
        getContentPane().add(tDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 245, 137, -1));

        getContentPane().add(cbCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 189, 137, -1));

        btnTambah.setBackground(new java.awt.Color(0, 102, 0));
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 39, 74, -1));

        btnUbah.setBackground(new java.awt.Color(255, 102, 0));
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        getContentPane().add(btnUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 39, -1, -1));

        btnHapus.setBackground(new java.awt.Color(153, 0, 0));
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 39, -1, -1));

        btnReset.setBackground(new java.awt.Color(153, 0, 153));
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 39, -1, -1));

        btnKembali.setBackground(new java.awt.Color(0, 102, 102));
        btnKembali.setForeground(new java.awt.Color(255, 255, 255));
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 39, 73, -1));

        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProduct);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 68, 436, 270));

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 180, 300));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Abackround2.jpeg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tDescriptionActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        new Dasboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        Product prd = new Product();
        Category ctg = new Category();
        try {
            prd.setProductName(tNama.getText());
            prd.setProductDescription(tDescription.getText());
            prd.setProductPrice(Integer.parseInt(tPrice.getText()));
        
        ctg.setCategoryName(cbCategory.getSelectedItem().toString());
        ResultSet rs = ctg.konversi();
        
        if (rs.next()) {
            int id = rs.getInt("categoryId");
            prd.setProductCategory(id);
        } 
         prd.TambahProduct();

        
        } catch (NumberFormatException  numberFormatException) {
            JOptionPane.showMessageDialog(null, "Eror : " + numberFormatException.getMessage());
        } catch(SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "Eror : " + sQLException.getMessage());
        }
        
        load_table();
        reset();

    }//GEN-LAST:event_btnTambahActionPerformed

    private void tblProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductMouseClicked
        // TODO add your handling code here:
        int row = tblProduct.getSelectedRow();
        
        if (row != -1) {
            String id = tblProduct.getValueAt(row, 0).toString();
            String name = tblProduct.getValueAt(row, 1).toString();
            String category = tblProduct.getValueAt(row, 2).toString();
            String description = tblProduct.getValueAt(row, 3).toString();
            String price = tblProduct.getValueAt(row, 4).toString();
            
            tID.setText(id);
            tNama.setText(name);
            tDescription.setText(description);
            tPrice.setText(price);
            cbCategory.setSelectedItem(category);
        
        }
    }//GEN-LAST:event_tblProductMouseClicked

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        Product prd = new Product();
        Category ctg = new Category();
    try {
            prd.setProductName(tNama.getText());
            prd.setProductDescription(tDescription.getText());
            prd.setProductPrice(Integer.parseInt(tPrice.getText()));
        
           ctg.setCategoryName(cbCategory.getSelectedItem().toString());
           ResultSet rs = ctg.konversi();
        
        if (rs.next()) {
            int id = rs.getInt("categoryId");
            prd.setProductCategory(id);
        } 
         prd.UbahProduct();

        
    } catch (NumberFormatException  numberFormatException) {
            JOptionPane.showMessageDialog(null, "Eror : " + numberFormatException.getMessage());
    } catch(SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "Eror : " + sQLException.getMessage());
    }
        
        load_table();
        reset();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        Product prd = new Product();
        prd.setProductId(Integer.parseInt(tID.getText()));
        
        prd.HapusProduct();
        load_table();
        reset();
    }//GEN-LAST:event_btnHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cbCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tDescription;
    private javax.swing.JTextField tID;
    private javax.swing.JTextField tNama;
    private javax.swing.JTextField tPrice;
    private javax.swing.JTable tblProduct;
    // End of variables declaration//GEN-END:variables
}
